#+title: Making all my devices the same

I'd like to have an identical set up across all my devices. My plan is
to install Guix as a package manager, running under Fedora. (Why
Fedora? Well, that's what my kids use, and that's what Isambard
uses. And then Asahi Linux, which runs on Apple silicon, is a Fedora
remix.) In the long run, I'd like to run GuixSD, but I suspect that is
going to be hard to set up until I have some experience with Guix.

** On Framework Desktop

*** Digression: BIOS

What is the bios? Apparently you need to hit F12 on boot; but I'm not
sure my keyboard is available. Oh: it is available (over USB-C) if
plugged in directly rather than through the monitor.

*** Install Fedora

1. Framework have
   [[https://guides.frame.work/Guide/Fedora+43+Installation+on+the+Framework+Desktop/674][an
   installation guide]].

2. I am installing ~Fedora-KDE-Desktop-Live-43-1.6.x86_64~

3. Apparently there is a decision to be made (in Step 3 of the
   Framework guide) about whether or not to enable (or disable) Secure
   Boot. It is unclear from the instructions whether doing nothing
   will leave Secure Boot enabled, or leave it disabled.

4. Huh.

   #+begin_quote
   The keyboard layout selected during installation is not used for
   the LUKS unlock screen. The early‑boot environment defaults to
   en‑US.
   #+end_quote

5. Somewhat amazingly, the Live USB system recognises my Keychron
   keyboard, 4K monitor, and Apple Magic Trackpad (Lightning version).

6. I'm only install on the main SSD for now. I have two SSDs, and the
   defaults seem to aggregate them both as a "btrfs subvolume". I
   don't want that -- I want /home on the secondary SSD. 

*** Update Fedora

Fedora update is:

#+begin_src
  sudo dfn update
#+end_src

*** Update firmware

Check current version with

#+begin_src
  sudo dmidecode --type bios
#+end_src

Check latest version
[[https://knowledgebase.frame.work/en_us/framework-desktop-bios-and-driver-releases-amd-ryzen-ai-max-300-series-BJHcn1Y4gg][from
Framework here]].

I'm on 03.03 and the latest is 03.04, so I did not bother to
update. (In fact, since then, I've just hit yes to update for all
updates.)

*** Fix partitions

There's [[https://btrfs.readthedocs.io/][documentation for btrfs]].

Actually, I am using KDE Partition Manager to create a new encrypted
partition on the second NVMe, with the same LUKS passphrase as the
other drive.

There's an option for permissions on "root only" or "everyone". I
don't know what this means, so I picked "everyone".

Same application, "edit mount point". I'm mounting this on /data, and
I ticked "do not prevent the system from booting of not mountable."

Then
#+begin_src
  sudo systemctl daemon-reload
#+end_src

**** Second attempt

Hm. I managed to format the second NVMe encrypted and mount it; but
not at boot time.

I'm restarting. Although, acutally, I think I have messed up. I should
have left the second NVMe as /data, rather than /home.

Well, let's see whether it automounts or not!

**** Third attempt

Final custom partitions:

- Main drive
  - vfat (EFI): 600 MB, mount at ~/boot/efi~
  - ext4: 2 GB, mount at ~/boot~
  - btrfs, LUKS2 encrypted, select "save passphrase"
    - btrfs, mount at ~/home~
    - btrfs, mount at ~/~

- Secondary drive
  - brtfs, LUKS2 encrypted, select "save passphrase"
    - btrfs, mount at ~/data~


*** On the todo queue

- Do I need RPM Fusion?
- What services are running? (See ~systemctl~)
- How many dnf packages are installed?
- What gets sourced when, when bash starts?
- How does systemd work?
- How do cgroups work?
- How do namespaces work?
  
**** Done   

- Stop asking for password on screensaver
- Move Dock to left
- Set device name: Put the name in ~/etc/hostname~.

* rpmfusion

Other, non-Redhat distributed software

#+begin_src sh
dnf lsudo dnf install
https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm
-E %fedora).noarch.rpm
https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm
-E %fedora).noarch.rpm
#+end_src

* Applications

** R

Somehow my setup compiles all R packages from source. That needed lots
of development libraries, but mostly it all works with dnf.

** QGIS

** Godot

I had to install an old version of Java. It is available from the
"adoptium" repository -- this appears to be quasi-official.

** Steam / wivrn

Urk. Apparently I need to swap out some accelerated codecs.

#+begin_src sh
sudo dnf swap mesa-va-drivers mesa-va-drivers-freeworld
sudo dnf swap mesa-vdpau-drivers mesa-vdpau-drivers-freeworld
#+end_src

And?

#+begin_src sh
sudo dnf swap ffmpeg-free ffmpeg --allowerasing
#+end_src

For wivrn:

#+begin_quote
Right click on game, go to Properties > General, and paste this in
Launch Options:

PRESSURE_VESSEL_IMPORT_OPENXR_1_RUNTIMES=1 VR_OVERRIDE=/run/host/usr/lib64/opencomposite/runtime %command%
#+end_quote

** TeX

Fedora is currently packaging texlive 2023, whereas the actual texlive
distribution is on 2025. I am going to try to install it with t1mgr.

1. Nuke existing install:
#+begin_src sh
  $ dnf remove "texlive*" 
  $ rm -rf ~/.texlive2023
  $ rm -rf /usr/share/texlive /etc/texlive /var/lib/texmf
#+end_src

2. Follow [[https://tug.org/texlive/quickinstall.html][instructions]]:

#+begin_src sh
  $ mkdir tmp
  $ cd tmp
  $ curl -L -o install-tl-unx.tar.gz https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz

  $ zcat < install-tl-unx.tar.gz | tar xf -
  $ cd install-tl-20260123/
  $ sudo dnf install perl-libwww-perl
#+end_src

Now the next part is tricky. texlive wants to go in
~/usr/local/texlive~, but it doesn't want to be installed as root. (Or
rather, it's happy with that, but it seems that there may be trouble
later.) So ... for now, I am going to give myself permissions for
~/usr/local/texlive~.

#+begin_src sh
  sudo mkdir /usr/local/texlive
  sudo chown jamie:jamie /usr/local/texlive
#+end_src

What I might do as a temporary measure on the shared device
(temporarily, before we get guix working!) is make a texlive owners group and
add everyone to it. For now, let's try to get it working.

Then
#+begin_src sh
  $ perl install-tl
#+end_src

It took 1min 20s to get through files beginning with "a", so I guess
this is going to take a while!

Okay, that produces the following, most of which I will ignore:
#+begin_src
 The following environment variables contain the string "tex"
 (case-independent).  If you're doing anything but adding personal
 directories to the system paths, they may well cause trouble somewhere
 while running TeX.  If you encounter problems, try unsetting them.

 Please ignore spurious matches unrelated to TeX. (To omit this check,
 set the environment variable TEXLIVE_INSTALL_ENV_NOCHECK.)

    TEXLIVE_INSTALL_NO_DISKCHECK=1
#+end_src

And:
#+begin_src sh
...
Add /usr/local/texlive/2025/texmf-dist/doc/man to MANPATH.
Add /usr/local/texlive/2025/texmf-dist/doc/info to INFOPATH.
Most importantly, add /usr/local/texlive/2025/bin/x86_64-linux
to your PATH for current and future sessions.
#+end_src

Although MANPATH and INFOPATH are not set by default, if you just set
them, tex will not find things. An initial colon is required. So, in ~.bash_profile~:
#+begin_src sh
  export MANPATH=":/usr/local/texlive/2025/texmf-dist/doc/man"
  export INFOPATH=":/usr/local/texlive/2025/texmf-dist/doc/info"
  PATH="$PATH:/usr/local/texlive/2025/bin/x68_64-linux"
#+end_src

And I need a bunch of perl modules:
#+begin_src sh
  sudo dnf install perl-Unicode-Normalize perl-sigtrap
#+end_src
