* Diary

** 15 Jan

- Installed Ubuntu. ssh in from host.
- Next: Full graphical install, is that usable?
- Next: Guix as a package manager


* Configuring Guix system

*** Setting up ssh

~ssh~ enabled during installation. To enable login with passwords,
#+begin_src
  ssh-copy-id user@host
#+end_src

*** Install packages as user

*** Add non-free software

** Extra packages

- Home Environment

  #+begin_src
    guix home import ~/src/guix-config
  #+end_src

  then edit ~~/src/guix-config/configuration.scm~ and run ~guix home
  reconfigure~. The first time I did this I got an error about a
  non-existing ~/var/guix/profiles/per-user/james~. However,
  installing a package (emacs) with ~git install~ created that
  directory.


** Minecraft

  #+begin_src
  guix install openjdk
  #+end_src

  Running Minecraft
  #+begin_src 
    java -Xmx4G -Xms4G -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -jar server.jar --world worlddir
  #+end_src
  
  
** Housekeeping

*** The locales thing

Tried ~guix install glibc-locales~ as root. That didn't work. Will try
updating the Guix system.

*** Update Guix

For packages:
#+begin_src
  guix pull
  hash guix
  guix package -u
#+end_src

For system:
#+begin_src
  guix pull
  sudo guix system reconfigure /etc/config.scm
#+end_src



* TODO

- Copy new config here
- Enable tailscale
- Figure out how to add emacs packages
- Disable password login except on console
  (I don't know how to do this.)


  

* Installing Guix in Ubuntu under VMWare


** Installation from ISO

I chose [Ubuntu Server 24.04.1 LTS](https://ubuntu.com/download/server/arm).

- I "updated to the new installer"
- English (UK) keyboard
- Defaults for all other options during install (eg, 20 GB hard drive)
  up to username
- Username james, password james
- Install OpenSSH

** After install

~sudo apt upgrade~

By default there is no root login.

The name of guest isn't known to host. (Why not??) 

Accessing the VM by ssh from host was not trivial. I got the IP
address from either ~ip addr~ in the VM or ~arp -a~ in the
host. However, the first time I tried to ssh I got "No route to
host". Perhaps it had to wake up the daemon or something?

** Install guix the package manager

Downloaded and ran this script:
https://git.savannah.gnu.org/gitweb/?p=guix.git;a=blob_plain;f=etc/guix-install.sh;hb=HEAD

That encouraged me to install nscd so I also ran
#+begin_src
  sudo apt install nscd
#+end_src

Then
#+begin_src
  guix pull
#+end_src
to update guix.



*** TODO
Install VMWare Fusion tools



** Install Guix as a package manager



** Linux commands

- ~ip addr~ :: What we used to do with ~ifconfig~.

- ~arp -a~ :: Discover what (some?) addresses we know about.
